name: Artifact

on: [push]

env: 
  ARTIFCT_NAME: myartifact
  
jobs:
  main:
  runs-on: ubuntu-latest
  steps:
    - name: check out the code
      use: actions/checkout@v2
    - name: upload artifact
      use: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
      
